const express = require('express')
const path = require('path')
const app = express()

app.use(express.json())

// Requring Routes Files
const home = require('./routes/home')
const riverrat = require('./routes/riverrat')
const sethplayer = require('./routes/sethplayer')
const hogs99 = require('./routes/hogs99')
const jackson123 = require('./routes/jackson123')
const goodguys = require('./routes/goodguys')
const austin2 = require('./routes/austin2')
const htownrc = require('./routes/htownrc')
const randyclay = require('./routes/randyclay')
const woodyma = require('./routes/woodyma')
const chancexiii = require('./routes/chancexiii')
const vangav = require('./routes/vangav')
const pspev = require('./routes/pspev')
const charsh = require('./routes/charsh')
const joeyspotsa = require('./routes/joeyspotsa')
const barcoon50 = require('./routes/barcoon50')
const nictex = require('./routes/nictex')
const ticonico = require('./routes/ticonico')
const eagscoot = require('./routes/eagscoot')
const arkrick = require('./routes/arkrick')
const m508 = require('./routes/m508')
const zs = require('./routes/zs')
const jd30 = require('./routes/jd30')
const mastkala1 = require('./routes/mastkala1')
const samfulk31 = require('./routes/samfulk31')
const jackhigh1 = require('./routes/jackhigh1')
const costaaa = require('./routes/costaaa')
const strfish21 = require('./routes/21strfish')
const strfish31 = require('./routes/31strfish')
const strfish41 = require('./routes/41strfish')
const strfish51 = require('./routes/51strfish')
const strfish61 = require('./routes/61strfish')

// Using Routes
app.use('/',home)
app.use('/riverrat',riverrat)
app.use('/sethplayer',sethplayer)
app.use('/hogs99',hogs99)
app.use('/jackson123',jackson123)
app.use('/goodguys',goodguys)
app.use('/austin2',austin2)
app.use('/htownrc',htownrc)
app.use('/randyclay',randyclay)
app.use('/woodyma',woodyma)
app.use('/chancexiii',chancexiii)
app.use('/vangav',vangav)
app.use('/pspev',pspev)
app.use('/charsh',charsh)
app.use('/joeyspotsa',joeyspotsa)
app.use('/barcoon50',barcoon50)
app.use('/nictex',nictex)
app.use('/ticonico',ticonico)
app.use('/eagscoot',eagscoot)
app.use('/arkrick',arkrick)
app.use('/m508',m508)
app.use('/zs',zs)
app.use('/jd30',jd30)
app.use('/mastkala1',mastkala1)
app.use('/samfulk31',samfulk31)
app.use('/jackhigh1',jackhigh1)
app.use('/costaaa',costaaa)
app.use('/21strfish',strfish21)
app.use('/31strfish',strfish31)
app.use('/41strfish',strfish41)
app.use('/51strfish',strfish51)
app.use('/61strfish',strfish61)

// Setting View Engine
app.set('view engine', 'pug')
app.set('views',path.join(__dirname, 'views'))
app.use(express.static(path.join(__dirname, 'views')))

app.listen(process.env.PORT || 3000)

// Closing the App
app.get('/stop', (req, res) => {
    res.redirect("/")
    process.exit(1)
})

